/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'carbon:dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'license',
    path: '/license',
    component: 'layout.base',
    meta: {
      title: 'license',
      i18nKey: 'route.license',
      icon: 'carbon:key',
      order: 3
    },
    children: [
      {
        name: 'license_list',
        path: '/license/list',
        component: 'view.license_list',
        meta: {
          title: 'license_list',
          i18nKey: 'route.license_list'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base',
    meta: {
      title: 'order',
      i18nKey: 'route.order',
      icon: 'carbon:shopping-cart',
      order: 4
    },
    children: [
      {
        name: 'order_list',
        path: '/order/list',
        component: 'view.order_list',
        meta: {
          title: 'order_list',
          i18nKey: 'route.order_list'
        }
      }
    ]
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'carbon:settings',
      order: 6
    }
  },
  {
    name: 'stats',
    path: '/stats',
    component: 'layout.base',
    meta: {
      title: 'stats',
      i18nKey: 'route.stats',
      icon: 'carbon:analytics',
      order: 5
    },
    children: [
      {
        name: 'stats_translation',
        path: '/stats/translation',
        component: 'view.stats_translation',
        meta: {
          title: 'stats_translation',
          i18nKey: 'route.stats_translation'
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'carbon:user-multiple',
      order: 2
    },
    children: [
      {
        name: 'user_agent',
        path: '/user/agent',
        component: 'view.user_agent',
        meta: {
          title: 'user_agent',
          i18nKey: 'route.user_agent',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['super']
        }
      },
      {
        name: 'user_device',
        path: '/user/device',
        component: 'view.user_device',
        meta: {
          title: 'user_device',
          i18nKey: 'route.user_device',
          icon: 'carbon:desktop',
          order: 1,
          roles: ['super', 'agent']
        }
      },
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          title: 'user_list',
          i18nKey: 'route.user_list'
        }
      },
      {
        name: 'user_role',
        path: '/user/role',
        component: 'view.user_role',
        meta: {
          title: 'user_role',
          i18nKey: 'route.user_role',
          icon: 'carbon:security',
          order: 3,
          roles: ['super']
        }
      }
    ]
  }
];
